### ISSUE TITLE
check if some ingest is already running

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-lib-ingest#4]
In order to avoid starting an ingest if already another one is running (or restoring) it would be nice if ingest scripts could check if on an instance some ingest is running and if so don't allow another ingest.

Such a feature would make automatic ingests (e.g. via github actions) more stable. E.g. in a use case like data-repo publishes a new version, publishing a new version triggers arche-ingest

**Comment by zozlak** [comment]
If I get it right and it's about syncing between ingestions running separately (e.g. as different instances of a github actions workflow), then it's partially solved already and partially unsolvable.

The problem is that an ARCHE instance has no clue about what a given transaction is planning to ingest so it's completely unable to tell if two transactions are "same" or not. Moreover, it will never be able to.

On the other hand if a transaction modifies a resource, it acquires a lock on it which makes it impossible to modify it by any other transaction until the lock is released (by a commit or rollback of the transaction which acquired it). So a transaction which comes later and tries to modify a locked resource will get "HTTP 409 Resource xxx locked". What happens next depends on how this error is handled by the ingestion scripts. Currently the arche-lib-ingest treats this error as a "recoverable" one and repeats update attempts until retries limit is reached but nothing prevents us from treating it as an hardly unrecoverable error which will abandon the whole ingestion (or to add a parameter allowing us to choose how to treat it).

**Comment by zozlak** [comment]
After a chat on the mattermost we'll go with treating the "locked by other transaction" error by unrecoverable one by the arche-lib-ingest which will allow an early ingestion failure when combined with the `ERROR_FAIL` error mode.

**Comment by zozlak** [comment]
The closer code inspection revealed that that's how it actually work already:

* If a resource is locked by another thransaction, the [arche-core throws HTTP 403 Owned by other transaction](https://github.com/acdh-oeaw/arche-core/blob/master/src/acdhOeaw/arche/core/Transaction.php#L190).
* As this error is not captured as recoverable by the `acdhOeaw\arche\lib\ingest\Indexer`/`acdhOeaw\arche\lib\ingest\MetadataCollection` (only HTTP 409 with selected error messages are - see [here](https://github.com/acdh-oeaw/arche-lib-ingest/blob/master/src/acdhOeaw/arche/lib/ingest/Indexer.php#L528) and [here](https://github.com/acdh-oeaw/arche-lib-ingest/blob/master/src/acdhOeaw/arche/lib/ingest/MetadataCollection.php#L311) and also [here](https://github.com/acdh-oeaw/arche-lib/blob/master/src/acdhOeaw/arche/lib/Repo.php#L345-L346)), it is interpreted as a non-recoverable error and its handling depends on the error mode.

Therefore it's enough to set the `$errorMode` parameter of the acdhOeaw\arche\lib\ingest\Indexer::index()`/`acdhOeaw\arche\lib\ingest\MetadataCollection::import()` to `ERRORMODE_FAIL` and the very first conflict should end the ingestion.

In arche-ingest script terms it means setting `--errorMode fail`.
